### ISSUE TITLE
New subtask parsing rules

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/txt#2]
Please check https://github.com/epogrebnyak/txt/blob/master/main.py#L18-L38.

No unittests yet, just keep `assert`'s in the body

**Comment by arwer13** [comment]
Ok, I'm going to look at it in the evening.

**Comment by arwer13** [comment]
Do I understand right:
- both doc1 and doc2 are allowed
- doc1 isn't actual yaml, just something similar?

**Comment by epogrebnyak** [comment]
No, doc2 shall be only set of rules, it replaces doc1

вт, 9 февр. 2016, 20:57, Veremeenko Artyom notifications@github.com:

**Comment by arwer13** [comment]
What should be done with `...` in 

```
[s] 23:30 06.02.2016 ... 2:30 09.02.2016 subtask description 3
```

added to description or 'forgotten'?

**Comment by epogrebnyak** [comment]
Lets add to description

вт, 9 февр. 2016, 21:47, Veremeenko Artyom notifications@github.com:

**Comment by arwer13** [comment]
To the beginning, to the end of description? Or save it's position relative to the description in whole line?

**Comment by epogrebnyak** [comment]
Please check code https://github.com/epogrebnyak/txt/blob/master/main.py to finish up subtask parsing

**Comment by arwer13** [comment]
Please specify what should be done with text between datetimes, it's still not clear for me:

> To the beginning, to the end of description? Or save it's position relative to the description in whole line?

And if it should be added to the description indeed, I guess I should change the assertions accordingly?

**Comment by arwer13** [comment]
I solved it somehow: https://github.com/epogrebnyak/txt/blob/master/main.py Is this what you'd like? What's about parsing whole tasks?

**Comment by epogrebnyak** [comment]
Will check and simplify
11 февр. 2016 г. 21:49 пользователь "Veremeenko Artyom" <
notifications@github.com> написал:

**Comment by arwer13** [comment]
Sorry, I didn't push yesterday evening! I'll do this today in the evening, when come home.

**Comment by epogrebnyak** [comment]
Я понял, что что-то нет, но не страшно. Пилить старое не надо, я упростил
тест. Посмотрите сообщение на upwork с комментарием

пт, 12 февр. 2016, 11:21, Veremeenko Artyom notifications@github.com:

**Comment by arwer13** [comment]
Ок.

**Comment by arwer13** [comment]
Запушил.

**Comment by epogrebnyak** [comment]
Большая просьба: 1) issues использовать не для переписки, а комментариев к самому issue. 2) "Запушил" - мне недостаточно, рядом должна быть ссылка на коммит. Спасибо.
